name: Security Scan

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - prod

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run security scan
      uses: aquasecurity/trivy-action@v0.8.0
      with:
        scan-type: filesystem
        severity: CRITICAL,HIGH
        exit-code: 1
